export const userActionTypes = {
    START_SIGNUP: 'START_SIGNUP',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    START_SIGNIN: 'START_SIGNIN',
    START_SIGNOUT: 'START_SIGNOUT',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNOUT_SUCCESS: 'SIGNOUT',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE'
}